-- ────────────────────────────────────────────────────────────
-- Migration: Tier 1 features schema
-- Project:   eq-field-app
-- Version:   3.4.3 (+ groundwork for future tier-1 features)
-- Supabase:  20260416190053_tier1_features_schema
-- Applied:   Prod  (nspbmirochztcjijmcrx) — 2026-04-16 ✓
-- ────────────────────────────────────────────────────────────
-- Bundles four related additions:
--   1. people.notify_roster  — opt-in roster change emails (WIRED in v3.4.3)
--   2. sites.site_lead_email — weekly site-lead roster email target (WIRED in v3.4.3)
--   3. leave_balances table  — manual AL/sick balance entry (table only, UI pending)
--   4. checkins table        — site check-in with optional GPS (table only, UI pending)
-- Also seeds app_config.weekly_roster_email flag (not yet consumed).
-- ────────────────────────────────────────────────────────────

-- ─── 1. Roster change notifications (opt-in per person) ───────
ALTER TABLE public.people
  ADD COLUMN IF NOT EXISTS notify_roster boolean DEFAULT false;

COMMENT ON COLUMN public.people.notify_roster IS
  'When true, person receives an email when their schedule is changed.';

-- ─── 2. Weekly roster email (site lead email + enable flag) ───
ALTER TABLE public.sites
  ADD COLUMN IF NOT EXISTS site_lead_email text;

COMMENT ON COLUMN public.sites.site_lead_email IS
  'Email for the site lead. Used for weekly roster auto-send.';

INSERT INTO public.app_config (key, value, org_id)
VALUES ('weekly_roster_email', 'false', '1eb831f9-aeae-4e57-b49e-9681e8f51e15')
ON CONFLICT (key) DO NOTHING;

-- ─── 3. Leave balances (manual entry per person) ──────────────
CREATE TABLE IF NOT EXISTS public.leave_balances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL,
  person_name text NOT NULL,
  al_balance numeric(5,1) DEFAULT 0,
  sick_balance numeric(5,1) DEFAULT 0,
  notes text,
  updated_by text,
  updated_at timestamptz DEFAULT now(),
  org_id uuid NOT NULL
);

ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_leave_balances ON public.leave_balances
  FOR SELECT USING (true);

CREATE POLICY anon_insert_leave_balances ON public.leave_balances
  FOR INSERT WITH CHECK (org_id IS NOT NULL);

CREATE POLICY anon_update_leave_balances ON public.leave_balances
  FOR UPDATE USING (org_id IS NOT NULL) WITH CHECK (org_id IS NOT NULL);

CREATE POLICY anon_delete_leave_balances ON public.leave_balances
  FOR DELETE USING (org_id IS NOT NULL);

-- ─── 4. Site check-ins (timestamp + GPS) ──────────────────────
CREATE TABLE IF NOT EXISTS public.checkins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_name text NOT NULL,
  site_code text NOT NULL,
  week text,
  checked_in_at timestamptz DEFAULT now(),
  latitude numeric(10,7),
  longitude numeric(10,7),
  org_id uuid NOT NULL
);

ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_checkins ON public.checkins
  FOR SELECT USING (true);

CREATE POLICY anon_insert_checkins ON public.checkins
  FOR INSERT WITH CHECK (org_id IS NOT NULL);

CREATE POLICY anon_delete_checkins ON public.checkins
  FOR DELETE USING (org_id IS NOT NULL);
